# Generated by Django 5.1.7 on 2025-08-26 19:53

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BTRFSRecoverySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('filesystem_path', models.CharField(max_length=500)),
                ('filesystem_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('mount_point', models.CharField(blank=True, max_length=500, null=True)),
                ('filesystem_type', models.CharField(choices=[('mounted', 'Mounted Filesystem'), ('unmounted', 'Unmounted Device'), ('detected', 'Auto-detected')], default='detected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('total_inodes', models.BigIntegerField(default=0)),
                ('recoverable_files', models.BigIntegerField(default=0)),
                ('session_data', models.JSONField(default=dict)),
                ('recovery_method', models.CharField(blank=True, choices=[('python_btrfs', 'Python-BTRFS'), ('btrfscue', 'BTRFScue'), ('manual_dd', 'Manual DD Commands'), ('hybrid', 'Hybrid Approach')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recovery_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BTRFSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('orphan_inodes', 'Orphaned Inodes'), ('deleted_dirs', 'Deleted Directory Entries'), ('orphaned_extents', 'Orphaned File Extents'), ('cow_nodes', 'COW Tree Nodes'), ('superblock', 'Superblock Analysis'), ('chunk_tree', 'Chunk Tree Analysis')], max_length=50)),
                ('objectid', models.BigIntegerField()),
                ('item_type', models.IntegerField()),
                ('offset_value', models.BigIntegerField()),
                ('generation', models.BigIntegerField()),
                ('metadata_json', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('is_recoverable', models.BooleanField(default=False)),
                ('estimated_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='recovery.btrfsrecoverysession')),
            ],
            options={
                'db_table': 'btrfs_analysis',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_recovery_method', models.CharField(choices=[('automatic', 'Automatic Detection'), ('python_btrfs', 'Python-BTRFS Only'), ('manual', 'Manual Commands Only')], default='automatic', max_length=20)),
                ('max_file_size', models.BigIntegerField(default=104857600)),
                ('auto_download', models.BooleanField(default=False)),
                ('show_technical_details', models.BooleanField(default=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('files_recovered', models.IntegerField(default=0)),
                ('bytes_recovered', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='RecoverableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('inode_number', models.BigIntegerField()),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('deletion_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('logical_address', models.BigIntegerField(blank=True, null=True)),
                ('physical_address', models.BigIntegerField(blank=True, null=True)),
                ('extent_count', models.IntegerField(default=0)),
                ('generation', models.BigIntegerField(blank=True, null=True)),
                ('recovery_status', models.CharField(choices=[('available', 'Available for Recovery'), ('in_progress', 'Recovery in Progress'), ('recovered', 'Successfully Recovered'), ('failed', 'Recovery Failed'), ('partial', 'Partially Recovered')], default='available', max_length=20)),
                ('recovery_confidence', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('recovered_size', models.BigIntegerField(blank=True, null=True)),
                ('integrity_score', models.FloatField(blank=True, null=True)),
                ('recovery_path', models.CharField(blank=True, max_length=500, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='recovery.btrfsrecoverysession')),
            ],
            options={
                'db_table': 'recoverable_files',
                'ordering': ['-recovery_confidence', '-file_size'],
                'unique_together': {('session', 'inode_number')},
            },
        ),
        migrations.CreateModel(
            name='RecoveryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('step_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('command_generated', models.TextField(blank=True, null=True)),
                ('file_uploaded', models.FileField(blank=True, null=True, upload_to='recovery_metadata/')),
                ('validation_result', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recovery.btrfsrecoverysession')),
            ],
            options={
                'db_table': 'recovery_steps',
                'ordering': ['step_number'],
                'unique_together': {('session', 'step_number')},
            },
        ),
    ]
