# Generated by Django 5.1.7 on 2025-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btrfsrecoverysession',
            name='session_data',
            field=models.JSONField(default=dict),
        ),
    ]
