# Generated by Django 5.1.7 on 2025-08-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_alter_btrfsrecoverysession_session_data'),
    ]

    operations = [
    ]
