# Generated by Django 5.1.7 on 2026-02-26 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0003_update_for_manual_commands'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recovery.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human-readable case name', max_length=255)),
                ('device_path', models.CharField(help_text='e.g. /dev/sdb or /dev/sdb1', max_length=500)),
                ('filesystem_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('SCANNING', 'Scanning'), ('ANALYZED', 'Analyzed'), ('RECOVERING', 'Recovering'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recovery_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='recovery.recoverycase'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('state_transition', 'State Transition'), ('artifact_upload', 'Artifact Upload'), ('candidate_generated', 'Candidate Generated'), ('recovery_command', 'Recovery Command'), ('recovery_result', 'Recovery Result'), ('chat', 'Chat'), ('error', 'Error')], max_length=30)),
                ('summary', models.CharField(max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Arbitrary structured data for this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='recovery.recoverycase')),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-created_at'],
                'permissions': [('view_audit', 'Can view audit log')],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('superblock', 'Superblock Dump'), ('chunk_tree', 'Chunk Tree'), ('fs_tree', 'FS Tree'), ('extent_tree', 'Extent Tree'), ('find_root', 'btrfs-find-root Output'), ('other', 'Other')], default='other', max_length=20)),
                ('raw_data', models.TextField(help_text='Raw text/JSON from the BTRFS command')),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured result after parser runs')),
                ('source_command', models.CharField(blank=True, default='', help_text='Command that produced this artifact', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='recovery.recoverycase')),
            ],
            options={
                'db_table': 'recovery_artifacts',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inode_number', models.BigIntegerField()),
                ('reconstructed_path', models.TextField(blank=True, default='', help_text='Best-effort path from DIR_ITEM records')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, default='unknown', max_length=50)),
                ('logical_address', models.BigIntegerField(blank=True, help_text='Logical byte address of first extent', null=True)),
                ('physical_address', models.BigIntegerField(blank=True, help_text='Physical LBA (after chunk map translation)', null=True)),
                ('extent_count', models.IntegerField(default=1)),
                ('generation', models.BigIntegerField(blank=True, null=True)),
                ('extent_map', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0, help_text='0.0 – 1.0 recovery confidence score')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('recovered', 'Recovered'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recovery.recoverycase')),
            ],
            options={
                'db_table': 'candidate_files',
                'ordering': ['-confidence', '-file_size'],
                'unique_together': {('case', 'inode_number')},
            },
        ),
    ]
