# Generated by Django 5.1.7 on 2026-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0003_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycase',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SCANNING', 'Scanning'), ('ANALYZED', 'Analyzed'), ('RECOVERING', 'Recovering'), ('VERIFYING', 'Verifying'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='CREATED', max_length=20),
        ),
    ]
