# Generated by Django 5.1.7 on 2026-03-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0004_core_recovery_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btrfsrecoverysession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recoverablefile',
            name='session',
        ),
        migrations.RemoveField(
            model_name='recoverystep',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='recoverablefile',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='recoverystep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BTRFSAnalysis',
        ),
        migrations.DeleteModel(
            name='RecoverableFile',
        ),
        migrations.DeleteModel(
            name='BTRFSRecoverySession',
        ),
        migrations.DeleteModel(
            name='RecoveryStep',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
